class PoFile: ...
class PoMessageIterator: ...
class PoMessage: ...

def double_input(input: int) -> int: ...

def po_file_read(filename: str) -> PoFile: ...

def po_message_iterator(file: PoFile) -> PoMessageIterator: ...

def po_next_message(iterator: PoMessageIterator) -> PoMessage: ...

def po_message_msgid(message: PoMessage) -> str: ...

def po_message_msgstr(message: PoMessage) -> str: ...
