[package]
name = "maturin-gettext-viewer"
version = "0.1.0"
edition = "2021"

[lib]
name = "maturin_gettext_viewer"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.152"
pyo3 = "0.19.0"

[build-dependencies]
cc = "1.0.83"
